name: Selenium Botu

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'  # Her 4 saatte bir çalışır

permissions:
  contents: write  # <-- BU ÇOK ÖNEMLİ: Bota dosya yazma izni verir

jobs:
  calistir:
    runs-on: ubuntu-latest

    steps:
      - name: Kodları Çek (Checkout)
        uses: actions/checkout@v3

      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Kütüphaneleri Yükle
        run: |
          pip install -r requirements.txt

      - name: Botu Çalıştır ve Hafızayı Güncelle
        env:
          MYL_LAB_EMAIL: ${{ secrets.MYL_LAB_EMAIL }}
          MY_LAB_PASSWORD: ${{ secrets.MY_LAB_PASSWORD }}
          MY_EMAIL: ${{ secrets.MY_EMAIL }}
          MY_PASSWORD: ${{ secrets.MY_PASSWORD }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: |
          python main.py
          
          # --- HAFIZA DOSYASINI GITHUB'A GERİ YÜKLEME ---
          git config --global user.name "Bot Bildirimi"
          git config --global user.email "bot@github.com"
          
          # memory.json değiştiyse commit et, değişmediyse hata verme
          git add memory.json
          git commit -m "Ödev sayısı güncellendi" || echo "Değişiklik yok"
          git push
